/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type DiscussionThreadReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "discussionThread";
};

export type ReaderProfileReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "readerProfile";
};

export type DiscussionPost = {
  _id: string;
  _type: "discussionPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  thread: DiscussionThreadReference;
  author: ReaderProfileReference;
  body: string;
  hasSpoilers?: boolean;
  moderationStatus?: "visible" | "hidden";
  isDemoActivity?: boolean;
};

export type CommunityClubReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "communityClub";
};

export type WorkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "work";
};

export type DiscussionThread = {
  _id: string;
  _type: "discussionThread";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  club: CommunityClubReference;
  work?: WorkReference;
  title: string;
  spoilerBoundary?: "none" | "unmarked" | "full";
  isDemoThread?: boolean;
};

export type PollReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "poll";
};

export type Vote = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  poll: PollReference;
  reader: ReaderProfileReference;
  option: WorkReference;
};

export type Poll = {
  _id: string;
  _type: "poll";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  club: CommunityClubReference;
  title: string;
  status?: "open" | "closed";
  options?: Array<
    {
      _key: string;
    } & WorkReference
  >;
  closesAt?: string;
  allowVoteChange?: boolean;
};

export type ClubMembership = {
  _id: string;
  _type: "clubMembership";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  club: CommunityClubReference;
  reader: ReaderProfileReference;
  role: "owner" | "moderator" | "member";
  status?: "active" | "left" | "removed";
};

export type CommunityClub = {
  _id: string;
  _type: "communityClub";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
  visibility?: "public" | "private";
  owner?: ReaderProfileReference;
  currentRead?: WorkReference;
  isDemoClub?: boolean;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type EditionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "edition";
};

export type ReadingProgress = {
  _id: string;
  _type: "readingProgress";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  reader: ReaderProfileReference;
  work: WorkReference;
  edition?: EditionReference;
  status: "wantToRead" | "currentlyReading" | "finished";
  percent?: number;
  startedAt?: string;
  finishedAt?: string;
  readCount?: number;
  importSource?: string;
};

export type ShelfReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "shelf";
};

export type ShelfEntry = {
  _id: string;
  _type: "shelfEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  edition?: EditionReference;
  shelf: ShelfReference;
  work: WorkReference;
  addedAt: string;
};

export type Shelf = {
  _id: string;
  _type: "shelf";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  owner: ReaderProfileReference;
  name: string;
  slug: Slug;
  kind: "wantToRead" | "currentlyReading" | "finished" | "custom";
  visibility?: "private" | "public";
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  reader: ReaderProfileReference;
  work: WorkReference;
  body: string;
  hasSpoilers?: boolean;
  visibility?: "private" | "public";
  moderationStatus?: "visible" | "hidden";
};

export type Rating = {
  _id: string;
  _type: "rating";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  reader: ReaderProfileReference;
  work: WorkReference;
  value: number;
};

export type ReaderProfile = {
  _id: string;
  _type: "readerProfile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId: string;
  displayName: string;
  avatarUrl?: string;
  bio?: string;
  profileVisibility?: "private" | "publicName";
  spaceColor?:
    | "cloud"
    | "blush"
    | "violet"
    | "clay"
    | "apricot"
    | "butter"
    | "mint"
    | "sky"
    | "navy";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tagline?: string;
  catalogDisclaimer?: string;
  ratingMethod?: string;
  minimumRatingCount?: number;
  openLibraryAttribution?: string;
};

export type CelebritySelectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "celebritySelection";
};

export type EditorialCollectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "editorialCollection";
};

export type EditorialReview = {
  _id: string;
  _type: "editorialReview";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  target:
    | CelebritySelectionReference
    | EditorialCollectionReference
    | EditionReference
    | WorkReference;
  status: "proposed" | "needsReview" | "approved" | "rejected";
  proposedBy?: string;
  reviewedBy?: string;
  reviewedAt?: string;
  note?: string;
};

export type CelebrityClubReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "celebrityClub";
};

export type CelebritySelection = {
  _id: string;
  _type: "celebritySelection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  featuredEditions?: Array<
    {
      _key: string;
    } & EditionReference
  >;
  club: CelebrityClubReference;
  year: number;
  month: number;
  works?: Array<
    {
      _key: string;
    } & WorkReference
  >;
  sourceUrl?: string;
  verifiedAt?: string;
  workflowStatus: "proposed" | "needsReview" | "approved" | "rejected";
  provenance?: SourceProvenance;
  emptyReason?: string;
};

export type SourceProvenance = {
  _type: "sourceProvenance";
  provider:
    "openLibrary" | "googleBooks" | "hardcover" | "editorial" | "officialSite";
  sourceId?: string;
  sourceUrl?: string;
  retrievedAt?: string;
  attribution?: string;
  licenseNote?: string;
};

export type CelebrityClub = {
  _id: string;
  _type: "celebrityClub";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  officialUrl: string;
  disclaimer?: string;
};

export type BestsellerSource = {
  _id: string;
  _type: "bestsellerSource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  officialUrl: string;
  lastVerifiedAt: string;
  notes?: string;
};

export type EditorialCollection = {
  _id: string;
  _type: "editorialCollection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  featuredEditions?: Array<
    {
      _key: string;
    } & EditionReference
  >;
  title: string;
  slug: Slug;
  description?: string;
  kind?: "discover" | "fantasyByYear" | "other";
  workflowStatus: "proposed" | "needsReview" | "approved" | "rejected";
  works?: Array<
    {
      _key: string;
    } & WorkReference
  >;
  year?: number;
  editorialLabel?: string;
};

export type GenreReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "genre";
};

export type Genre = {
  _id: string;
  _type: "genre";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  parent?: GenreReference;
  description?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  bio?: string;
  openLibraryAuthorKey?: string;
  provenance?: SourceProvenance;
  editorialLocked?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Edition = {
  _id: string;
  _type: "edition";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  importKey?: string;
  googleBooksId?: string;
  coverCheckedAt?: string;
  publicationDate?: string;
  cover?: {
    url?: string;
    source?: "google" | "openLibrary" | "manual";
  };
  needsCover?: boolean;
  title?: string;
  work: WorkReference;
  isbn13?: string;
  isbn10?: string;
  openLibraryEditionKey?: string;
  format?: "hardcover" | "paperback" | "ebook" | "audiobook" | "other";
  market?: string;
  publisher?: string;
  onSaleDate?: string;
  isReprint?: boolean;
  firstPublicationOfWork?: boolean;
  coverOpenLibraryId?: string;
  coverUrl?: string;
  coverOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  provenance?: SourceProvenance;
  editorialLocked?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Work = {
  _id: string;
  _type: "work";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  goodreadsBookId?: string;
  importKey?: string;
  title: string;
  slug: Slug;
  subtitle?: string;
  authors?: Array<
    {
      _key: string;
    } & AuthorReference
  >;
  genres?: Array<
    {
      _key: string;
    } & GenreReference
  >;
  description?: string;
  firstPublicationYear?: number;
  firstPublicationDate?: string;
  openLibraryWorkKey?: string;
  provenance?: SourceProvenance;
  ratingStats?: RatingStats;
  editorialLocked?: boolean;
};

export type RatingStats = {
  _type: "ratingStats";
  average?: number;
  count?: number;
  updatedAt?: string;
};

export type CatalogImportIdentity = {
  _id: string;
  _type: "catalogImportIdentity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  importKey?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | DiscussionThreadReference
  | ReaderProfileReference
  | DiscussionPost
  | CommunityClubReference
  | WorkReference
  | DiscussionThread
  | PollReference
  | Vote
  | Poll
  | ClubMembership
  | CommunityClub
  | Slug
  | EditionReference
  | ReadingProgress
  | ShelfReference
  | ShelfEntry
  | Shelf
  | Review
  | Rating
  | ReaderProfile
  | SiteSettings
  | CelebritySelectionReference
  | EditorialCollectionReference
  | EditorialReview
  | CelebrityClubReference
  | CelebritySelection
  | SourceProvenance
  | CelebrityClub
  | BestsellerSource
  | EditorialCollection
  | GenreReference
  | Genre
  | Author
  | SanityImageAssetReference
  | Edition
  | SanityImageCrop
  | SanityImageHotspot
  | AuthorReference
  | Work
  | RatingStats
  | CatalogImportIdentity
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    tagline,    catalogDisclaimer,    ratingMethod,    minimumRatingCount,    openLibraryAttribution  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      tagline: null;
      catalogDisclaimer: null;
      ratingMethod: null;
      minimumRatingCount: null;
      openLibraryAttribution: null;
    }
  | {
      tagline: string | null;
      catalogDisclaimer: string | null;
      ratingMethod: string | null;
      minimumRatingCount: number | null;
      openLibraryAttribution: string | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: DISCOVER_COLLECTIONS_QUERY
// Query: *[_type == "editorialCollection" && workflowStatus == "approved" && kind == "discover"] | order(title asc){    _id,    title,    "slug": slug.current,    description,    "works": works[]->{   _id,  title,  "slug": slug.current,  firstPublicationYear,  description,  ratingStats,  "authors": authors[]->{ _id, name, "slug": slug.current },  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop}}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{      _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop},    isReprint,    firstPublicationOfWork,    onSaleDate,    market  }) }  }
export type DISCOVER_COLLECTIONS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  works: Array<{
    _id: string;
    title: string;
    slug: string;
    firstPublicationYear: number | null;
    description: string | null;
    ratingStats: RatingStats | null;
    authors: Array<{
      _id: string;
      name: string;
      slug: string;
    }> | null;
    genres: Array<{
      _id: string;
      title: string;
      slug: string;
      parentSlug: string | null;
    }> | null;
    cover:
      | {
          _id: string;
          isbn10: string | null;
          isbn13: string | null;
          cover: {
            url?: string;
            source?: "google" | "manual" | "openLibrary";
          } | null;
          coverUrl: string | null;
          coverOpenLibraryId: string | null;
          needsCover: boolean | null;
          coverOverride: {
            asset: {
              _id: string;
              url: string;
            } | null;
            alt: string | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
          } | null;
          isReprint: boolean | null;
          firstPublicationOfWork: boolean | null;
          onSaleDate: string | null;
          market: string | null;
        }
      | {
          _id: string;
          isbn10: string | null;
          isbn13: string | null;
          cover: {
            url?: string;
            source?: "google" | "manual" | "openLibrary";
          } | null;
          coverUrl: string | null;
          coverOpenLibraryId: string | null;
          needsCover: boolean | null;
          coverOverride: {
            asset: {
              _id: string;
              url: string;
            } | null;
            alt: string | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
          } | null;
        }
      | null;
  }> | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: CURATED_COLLECTIONS_QUERY
// Query: *[_type == "curatedCollection"] | order(lastSyncedAt desc){    _id,    title,    "slug": slug.current,    collectionType,    description,    curator,    source,    totalSelections,    "books": books | order(selectionNumber desc)[0...24]{      selectionNumber,      month,      year,      selectionDate,      "book": book->{   _id,  title,  authors,  "slug": slug.current,  googleBooksId,  publishedDate,  isbn10, isbn13, coverOverride{asset->{_id, url}, alt, hotspot, crop},  "edition": edition->{  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop}},  cover }    }  }
export type CURATED_COLLECTIONS_QUERY_RESULT = Array<never>;

// Source: ../src/sanity/queries.ts
// Variable: CURATED_COLLECTION_BY_SLUG_QUERY
// Query: *[_type == "curatedCollection" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    collectionType,    description,    curator,    source,    totalSelections,    "books": books | order(selectionNumber desc){      selectionNumber,      month,      year,      selectionDate,      "book": book->{   _id,  title,  authors,  "slug": slug.current,  googleBooksId,  publishedDate,  isbn10, isbn13, coverOverride{asset->{_id, url}, alt, hotspot, crop},  "edition": edition->{  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop}},  cover }    }  }
export type CURATED_COLLECTION_BY_SLUG_QUERY_RESULT = null;

// Source: ../src/sanity/queries.ts
// Variable: COLLECTION_BY_SLUG_QUERY
// Query: *[_type == "editorialCollection" && slug.current == $slug && workflowStatus == "approved"][0]{    _id,    title,    "slug": slug.current,    description,    editorialLabel,    kind,    "works": works[]->{   _id,  title,  "slug": slug.current,  firstPublicationYear,  description,  ratingStats,  "authors": authors[]->{ _id, name, "slug": slug.current },  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop}}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{      _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop},    isReprint,    firstPublicationOfWork,    onSaleDate,    market  }) }  }
export type COLLECTION_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  editorialLabel: string | null;
  kind: "discover" | "fantasyByYear" | "other" | null;
  works: Array<{
    _id: string;
    title: string;
    slug: string;
    firstPublicationYear: number | null;
    description: string | null;
    ratingStats: RatingStats | null;
    authors: Array<{
      _id: string;
      name: string;
      slug: string;
    }> | null;
    genres: Array<{
      _id: string;
      title: string;
      slug: string;
      parentSlug: string | null;
    }> | null;
    cover:
      | {
          _id: string;
          isbn10: string | null;
          isbn13: string | null;
          cover: {
            url?: string;
            source?: "google" | "manual" | "openLibrary";
          } | null;
          coverUrl: string | null;
          coverOpenLibraryId: string | null;
          needsCover: boolean | null;
          coverOverride: {
            asset: {
              _id: string;
              url: string;
            } | null;
            alt: string | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
          } | null;
          isReprint: boolean | null;
          firstPublicationOfWork: boolean | null;
          onSaleDate: string | null;
          market: string | null;
        }
      | {
          _id: string;
          isbn10: string | null;
          isbn13: string | null;
          cover: {
            url?: string;
            source?: "google" | "manual" | "openLibrary";
          } | null;
          coverUrl: string | null;
          coverOpenLibraryId: string | null;
          needsCover: boolean | null;
          coverOverride: {
            asset: {
              _id: string;
              url: string;
            } | null;
            alt: string | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
          } | null;
        }
      | null;
  }> | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: WORK_BY_SLUG_QUERY
// Query: *[_type == "work" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  firstPublicationYear,  description,  ratingStats,  "authors": authors[]->{ _id, name, "slug": slug.current },  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop}}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{      _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop},    isReprint,    firstPublicationOfWork,    onSaleDate,    market  }),    subtitle,    firstPublicationDate,    openLibraryWorkKey,    provenance,    "editions": *[_type == "edition" && work._ref == ^._id] | order(onSaleDate desc){      _id,      title,      isbn13,      format,      market,      publisher,      onSaleDate,      isReprint,      firstPublicationOfWork,        _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop}    }  }
export type WORK_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  firstPublicationYear: number | null;
  description: string | null;
  ratingStats: RatingStats | null;
  authors: Array<{
    _id: string;
    name: string;
    slug: string;
  }> | null;
  genres: Array<{
    _id: string;
    title: string;
    slug: string;
    parentSlug: string | null;
  }> | null;
  cover: {
    _id: string;
    isbn10: string | null;
    isbn13: string | null;
    cover: {
      url?: string;
      source?: "google" | "manual" | "openLibrary";
    } | null;
    coverUrl: string | null;
    coverOpenLibraryId: string | null;
    needsCover: boolean | null;
    coverOverride: {
      asset: {
        _id: string;
        url: string;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    isReprint: boolean | null;
    firstPublicationOfWork: boolean | null;
    onSaleDate: string | null;
    market: string | null;
  } | null;
  subtitle: string | null;
  firstPublicationDate: string | null;
  openLibraryWorkKey: string | null;
  provenance: SourceProvenance | null;
  editions: Array<{
    _id: string;
    title: string | null;
    isbn13: string | null;
    format: "audiobook" | "ebook" | "hardcover" | "other" | "paperback" | null;
    market: string | null;
    publisher: string | null;
    onSaleDate: string | null;
    isReprint: boolean | null;
    firstPublicationOfWork: boolean | null;
    isbn10: string | null;
    cover: {
      url?: string;
      source?: "google" | "manual" | "openLibrary";
    } | null;
    coverUrl: string | null;
    coverOpenLibraryId: string | null;
    needsCover: boolean | null;
    coverOverride: {
      asset: {
        _id: string;
        url: string;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  }>;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: GENRES_QUERY
// Query: *[_type == "genre"] | order(title asc){    _id,    title,    "slug": slug.current,    description,    "parent": parent->{ title, "slug": slug.current }  }
export type GENRES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  parent: {
    title: string;
    slug: string;
  } | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: BESTSELLER_SOURCES_QUERY
// Query: *[_type == "bestsellerSource"] | order(name asc){    _id,    name,    officialUrl,    lastVerifiedAt,    notes  }
export type BESTSELLER_SOURCES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  officialUrl: string;
  lastVerifiedAt: string;
  notes: string | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: CELEBRITY_CLUBS_QUERY
// Query: *[_type == "celebrityClub"] | order(name asc){    _id,    name,    "slug": slug.current,    officialUrl,    disclaimer,    "selections": *[_type == "celebritySelection" && club._ref == ^._id && workflowStatus == "approved"] | order(year desc, month desc){      _id,      year,      month,      sourceUrl,      verifiedAt,      emptyReason,      "works": works[]->{   _id,  title,  "slug": slug.current,  firstPublicationYear,  description,  ratingStats,  "authors": authors[]->{ _id, name, "slug": slug.current },  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop}}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{      _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop},    isReprint,    firstPublicationOfWork,    onSaleDate,    market  }) }    }  }
export type CELEBRITY_CLUBS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  officialUrl: string;
  disclaimer: string | null;
  selections: Array<{
    _id: string;
    year: number;
    month: number;
    sourceUrl: string | null;
    verifiedAt: string | null;
    emptyReason: string | null;
    works: Array<{
      _id: string;
      title: string;
      slug: string;
      firstPublicationYear: number | null;
      description: string | null;
      ratingStats: RatingStats | null;
      authors: Array<{
        _id: string;
        name: string;
        slug: string;
      }> | null;
      genres: Array<{
        _id: string;
        title: string;
        slug: string;
        parentSlug: string | null;
      }> | null;
      cover:
        | {
            _id: string;
            isbn10: string | null;
            isbn13: string | null;
            cover: {
              url?: string;
              source?: "google" | "manual" | "openLibrary";
            } | null;
            coverUrl: string | null;
            coverOpenLibraryId: string | null;
            needsCover: boolean | null;
            coverOverride: {
              asset: {
                _id: string;
                url: string;
              } | null;
              alt: string | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
            } | null;
            isReprint: boolean | null;
            firstPublicationOfWork: boolean | null;
            onSaleDate: string | null;
            market: string | null;
          }
        | {
            _id: string;
            isbn10: string | null;
            isbn13: string | null;
            cover: {
              url?: string;
              source?: "google" | "manual" | "openLibrary";
            } | null;
            coverUrl: string | null;
            coverOpenLibraryId: string | null;
            needsCover: boolean | null;
            coverOverride: {
              asset: {
                _id: string;
                url: string;
              } | null;
              alt: string | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
            } | null;
          }
        | null;
    }> | null;
  }>;
}>;

// Source: ../src/sanity/queries.ts
// Variable: CELEBRITY_CLUB_BY_SLUG_QUERY
// Query: *[_type == "celebrityClub" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    officialUrl,    disclaimer,    "selections": *[_type == "celebritySelection" && club._ref == ^._id && workflowStatus == "approved"] | order(year desc, month desc){      _id,      year,      month,      sourceUrl,      verifiedAt,      emptyReason,      "works": works[]->{   _id,  title,  "slug": slug.current,  firstPublicationYear,  description,  ratingStats,  "authors": authors[]->{ _id, name, "slug": slug.current },  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop}}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{      _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop},    isReprint,    firstPublicationOfWork,    onSaleDate,    market  }) }    }  }
export type CELEBRITY_CLUB_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  officialUrl: string;
  disclaimer: string | null;
  selections: Array<{
    _id: string;
    year: number;
    month: number;
    sourceUrl: string | null;
    verifiedAt: string | null;
    emptyReason: string | null;
    works: Array<{
      _id: string;
      title: string;
      slug: string;
      firstPublicationYear: number | null;
      description: string | null;
      ratingStats: RatingStats | null;
      authors: Array<{
        _id: string;
        name: string;
        slug: string;
      }> | null;
      genres: Array<{
        _id: string;
        title: string;
        slug: string;
        parentSlug: string | null;
      }> | null;
      cover:
        | {
            _id: string;
            isbn10: string | null;
            isbn13: string | null;
            cover: {
              url?: string;
              source?: "google" | "manual" | "openLibrary";
            } | null;
            coverUrl: string | null;
            coverOpenLibraryId: string | null;
            needsCover: boolean | null;
            coverOverride: {
              asset: {
                _id: string;
                url: string;
              } | null;
              alt: string | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
            } | null;
            isReprint: boolean | null;
            firstPublicationOfWork: boolean | null;
            onSaleDate: string | null;
            market: string | null;
          }
        | {
            _id: string;
            isbn10: string | null;
            isbn13: string | null;
            cover: {
              url?: string;
              source?: "google" | "manual" | "openLibrary";
            } | null;
            coverUrl: string | null;
            coverOpenLibraryId: string | null;
            needsCover: boolean | null;
            coverOverride: {
              asset: {
                _id: string;
                url: string;
              } | null;
              alt: string | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
            } | null;
          }
        | null;
    }> | null;
  }>;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: COMMUNITY_CLUBS_QUERY
// Query: *[_type == "communityClub" && visibility == "public"] | order(name asc){    _id,    name,    "slug": slug.current,    description,    isDemoClub,    "currentRead": currentRead->{   _id,  title,  "slug": slug.current,  firstPublicationYear,  description,  ratingStats,  "authors": authors[]->{ _id, name, "slug": slug.current },  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop}}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{      _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop},    isReprint,    firstPublicationOfWork,    onSaleDate,    market  }) }  }
export type COMMUNITY_CLUBS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  isDemoClub: boolean | null;
  currentRead: {
    _id: string;
    title: string;
    slug: string;
    firstPublicationYear: number | null;
    description: string | null;
    ratingStats: RatingStats | null;
    authors: Array<{
      _id: string;
      name: string;
      slug: string;
    }> | null;
    genres: Array<{
      _id: string;
      title: string;
      slug: string;
      parentSlug: string | null;
    }> | null;
    cover: {
      _id: string;
      isbn10: string | null;
      isbn13: string | null;
      cover: {
        url?: string;
        source?: "google" | "manual" | "openLibrary";
      } | null;
      coverUrl: string | null;
      coverOpenLibraryId: string | null;
      needsCover: boolean | null;
      coverOverride: {
        asset: {
          _id: string;
          url: string;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      isReprint: boolean | null;
      firstPublicationOfWork: boolean | null;
      onSaleDate: string | null;
      market: string | null;
    } | null;
  } | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: COMMUNITY_CLUB_BY_SLUG_QUERY
// Query: *[_type == "communityClub" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    description,    visibility,    isDemoClub,    "currentRead": currentRead->{   _id,  title,  "slug": slug.current,  firstPublicationYear,  description,  ratingStats,  "authors": authors[]->{ _id, name, "slug": slug.current },  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop}}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{      _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,  coverOverride{asset->{_id, url}, alt, hotspot, crop},    isReprint,    firstPublicationOfWork,    onSaleDate,    market  }) }  }
export type COMMUNITY_CLUB_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  visibility: "private" | "public" | null;
  isDemoClub: boolean | null;
  currentRead: {
    _id: string;
    title: string;
    slug: string;
    firstPublicationYear: number | null;
    description: string | null;
    ratingStats: RatingStats | null;
    authors: Array<{
      _id: string;
      name: string;
      slug: string;
    }> | null;
    genres: Array<{
      _id: string;
      title: string;
      slug: string;
      parentSlug: string | null;
    }> | null;
    cover: {
      _id: string;
      isbn10: string | null;
      isbn13: string | null;
      cover: {
        url?: string;
        source?: "google" | "manual" | "openLibrary";
      } | null;
      coverUrl: string | null;
      coverOpenLibraryId: string | null;
      needsCover: boolean | null;
      coverOverride: {
        asset: {
          _id: string;
          url: string;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      isReprint: boolean | null;
      firstPublicationOfWork: boolean | null;
      onSaleDate: string | null;
      market: string | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    tagline,\n    catalogDisclaimer,\n    ratingMethod,\n    minimumRatingCount,\n    openLibraryAttribution\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "editorialCollection" && workflowStatus == "approved" && kind == "discover"] | order(title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "works": works[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  firstPublicationYear,\n  description,\n  ratingStats,\n  "authors": authors[]->{ _id, name, "slug": slug.current },\n  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },\n  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{\n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{\n    \n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n,\n    isReprint,\n    firstPublicationOfWork,\n    onSaleDate,\n    market\n  })\n }\n  }\n': DISCOVER_COLLECTIONS_QUERY_RESULT;
    '\n  *[_type == "curatedCollection"] | order(lastSyncedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    collectionType,\n    description,\n    curator,\n    source,\n    totalSelections,\n    "books": books | order(selectionNumber desc)[0...24]{\n      selectionNumber,\n      month,\n      year,\n      selectionDate,\n      "book": book->{ \n  _id,\n  title,\n  authors,\n  "slug": slug.current,\n  googleBooksId,\n  publishedDate,\n  isbn10, isbn13, coverOverride{asset->{_id, url}, alt, hotspot, crop},\n  "edition": edition->{\n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n},\n  cover\n }\n    }\n  }\n': CURATED_COLLECTIONS_QUERY_RESULT;
    '\n  *[_type == "curatedCollection" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    collectionType,\n    description,\n    curator,\n    source,\n    totalSelections,\n    "books": books | order(selectionNumber desc){\n      selectionNumber,\n      month,\n      year,\n      selectionDate,\n      "book": book->{ \n  _id,\n  title,\n  authors,\n  "slug": slug.current,\n  googleBooksId,\n  publishedDate,\n  isbn10, isbn13, coverOverride{asset->{_id, url}, alt, hotspot, crop},\n  "edition": edition->{\n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n},\n  cover\n }\n    }\n  }\n': CURATED_COLLECTION_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "editorialCollection" && slug.current == $slug && workflowStatus == "approved"][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    editorialLabel,\n    kind,\n    "works": works[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  firstPublicationYear,\n  description,\n  ratingStats,\n  "authors": authors[]->{ _id, name, "slug": slug.current },\n  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },\n  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{\n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{\n    \n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n,\n    isReprint,\n    firstPublicationOfWork,\n    onSaleDate,\n    market\n  })\n }\n  }\n': COLLECTION_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "work" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  firstPublicationYear,\n  description,\n  ratingStats,\n  "authors": authors[]->{ _id, name, "slug": slug.current },\n  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },\n  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{\n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{\n    \n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n,\n    isReprint,\n    firstPublicationOfWork,\n    onSaleDate,\n    market\n  })\n,\n    subtitle,\n    firstPublicationDate,\n    openLibraryWorkKey,\n    provenance,\n    "editions": *[_type == "edition" && work._ref == ^._id] | order(onSaleDate desc){\n      _id,\n      title,\n      isbn13,\n      format,\n      market,\n      publisher,\n      onSaleDate,\n      isReprint,\n      firstPublicationOfWork,\n      \n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n\n    }\n  }\n': WORK_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "genre"] | order(title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "parent": parent->{ title, "slug": slug.current }\n  }\n': GENRES_QUERY_RESULT;
    '\n  *[_type == "bestsellerSource"] | order(name asc){\n    _id,\n    name,\n    officialUrl,\n    lastVerifiedAt,\n    notes\n  }\n': BESTSELLER_SOURCES_QUERY_RESULT;
    '\n  *[_type == "celebrityClub"] | order(name asc){\n    _id,\n    name,\n    "slug": slug.current,\n    officialUrl,\n    disclaimer,\n    "selections": *[_type == "celebritySelection" && club._ref == ^._id && workflowStatus == "approved"] | order(year desc, month desc){\n      _id,\n      year,\n      month,\n      sourceUrl,\n      verifiedAt,\n      emptyReason,\n      "works": works[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  firstPublicationYear,\n  description,\n  ratingStats,\n  "authors": authors[]->{ _id, name, "slug": slug.current },\n  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },\n  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{\n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{\n    \n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n,\n    isReprint,\n    firstPublicationOfWork,\n    onSaleDate,\n    market\n  })\n }\n    }\n  }\n': CELEBRITY_CLUBS_QUERY_RESULT;
    '\n  *[_type == "celebrityClub" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    officialUrl,\n    disclaimer,\n    "selections": *[_type == "celebritySelection" && club._ref == ^._id && workflowStatus == "approved"] | order(year desc, month desc){\n      _id,\n      year,\n      month,\n      sourceUrl,\n      verifiedAt,\n      emptyReason,\n      "works": works[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  firstPublicationYear,\n  description,\n  ratingStats,\n  "authors": authors[]->{ _id, name, "slug": slug.current },\n  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },\n  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{\n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{\n    \n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n,\n    isReprint,\n    firstPublicationOfWork,\n    onSaleDate,\n    market\n  })\n }\n    }\n  }\n': CELEBRITY_CLUB_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "communityClub" && visibility == "public"] | order(name asc){\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    isDemoClub,\n    "currentRead": currentRead->{ \n  _id,\n  title,\n  "slug": slug.current,\n  firstPublicationYear,\n  description,\n  ratingStats,\n  "authors": authors[]->{ _id, name, "slug": slug.current },\n  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },\n  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{\n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{\n    \n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n,\n    isReprint,\n    firstPublicationOfWork,\n    onSaleDate,\n    market\n  })\n }\n  }\n': COMMUNITY_CLUBS_QUERY_RESULT;
    '\n  *[_type == "communityClub" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    visibility,\n    isDemoClub,\n    "currentRead": currentRead->{ \n  _id,\n  title,\n  "slug": slug.current,\n  firstPublicationYear,\n  description,\n  ratingStats,\n  "authors": authors[]->{ _id, name, "slug": slug.current },\n  "genres": genres[]->{ _id, title, "slug": slug.current, "parentSlug": parent->slug.current },\n  "cover": coalesce((^.featuredEditions[]->)[work._ref == ^._id][0]{\n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n}, *[_type == "edition" && work._ref == ^._id] | order(defined(coverOverride.asset) desc, defined(cover.url) desc, defined(coverUrl) desc, onSaleDate desc, firstPublicationOfWork desc)[0]{\n    \n  _id, isbn10, isbn13, cover, coverUrl, coverOpenLibraryId, needsCover,\n  coverOverride{asset->{_id, url}, alt, hotspot, crop}\n,\n    isReprint,\n    firstPublicationOfWork,\n    onSaleDate,\n    market\n  })\n }\n  }\n': COMMUNITY_CLUB_BY_SLUG_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
